version: "3"

services:
  php:
    image: wodby/wordpress:$WORDPRESS_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      WP_AUTH_KEY: $WP_AUTH_KEY
      WP_AUTH_SALT: $WP_AUTH_SALT
      WP_SECURE_AUTH_KEY: $WP_SECURE_AUTH_KEY
      WP_SECURE_AUTH_SALT: $WP_SECURE_AUTH_SALT
      WP_LOGGED_IN_KEY: $WP_LOGGED_IN_KEY
      WP_LOGGED_IN_SALT: $WP_LOGGED_IN_SALT
      WP_NONCE_KEY: $WP_NONCE_KEY
      WP_NONCE_SALT: $WP_NONCE_SALT
    volumes:
    - codebase:/var/www/html

  crond:
    image: wodby/wordpress:$WORDPRESS_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  nginx:
    volumes:
    - codebase:/var/www/html

#  webgrind:
#    volumes:
#    - codebase:/mnt/codebase

volumes:
  codebase:
